apiVersion: v1
kind: Secret
metadata:
  name: ensemble-secrets
  namespace: ensemble-grafana
type: Opaque
stringData:
  POSTGRES_URL: jdbc:postgresql://inventory-postgres.example:5432/ensemble_inventory
  POSTGRES_USER: ensemble
  POSTGRES_PASSWORD: replace-me
  ALLOWED_CORS_ORIGINS: https://ensemble-retail.com,https://www.ensemble-retail.com,https://ensemble-grafana.com,https://www.ensemble-grafana.com
  GRAFANA_CLOUD_OTLP_ENDPOINT: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
  GRAFANA_CLOUD_INSTANCE_ID: replace-me
  GRAFANA_CLOUD_API_KEY: replace-me
  COGNITO_USER_POOL_ID: replace-me
  COGNITO_CLIENT_ID: replace-me
  COGNITO_ISSUER_URI: https://cognito-idp.us-east-1.amazonaws.com/replace-me
  API_TEST_KEY: replace-me
