export const fallbackProducts = [
  {
    id: 'mens-shell-alpha',
    name: "Men's Alpine Shell Jacket",
    department: 'mens',
    category: 'Shells',
    price: 340,
    colors: ['Graphite', 'Lichen', 'Signal Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'Storm ready',
    rating: 4.8,
    stock: 42,
    image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'mens-midlayer-grid',
    name: "Men's Grid Fleece Midlayer",
    department: 'mens',
    category: 'Mid Layers',
    originalPrice: 128,
    price: 109,
    colors: ['Pine', 'Black', 'Ice'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: '15% off',
    rating: 4.7,
    stock: 65,
    image: 'https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'mens-trail-pant',
    name: "Men's Traverse Trail Pant",
    department: 'mens',
    category: 'Pants',
    originalPrice: 156,
    price: 133,
    colors: ['Basalt', 'Moss'],
    sizes: ['28', '30', '32', '34', '36'],
    badge: '15% off',
    rating: 4.9,
    stock: 38,
    image: 'https://images.unsplash.com/photo-1617612283917-5268a9d94651?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'mens-daypack-22',
    name: "Men's Route 22 Pack",
    department: 'mens',
    category: 'Packs',
    price: 118,
    colors: ['Black', 'Cobalt', 'Clay'],
    sizes: ['22L'],
    badge: 'Online exclusive',
    rating: 4.6,
    stock: 51,
    image: 'https://images.unsplash.com/photo-1622560480654-d96214fdc887?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'womens-base-merino',
    name: "Women's Merino Base Crew",
    department: 'womens',
    category: 'Base Layers',
    price: 88,
    colors: ['Heather', 'Night', 'Sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'Warmth without bulk',
    rating: 4.5,
    stock: 72,
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'womens-softshell-hoody',
    name: "Women's Softshell Hoody",
    department: 'womens',
    category: 'Shells',
    originalPrice: 220,
    price: 187,
    colors: ['Mineral', 'Black', 'Juniper'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: '15% off',
    rating: 4.7,
    stock: 58,
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'womens-climb-pant',
    name: "Women's Climb Pant",
    department: 'womens',
    category: 'Pants',
    price: 148,
    colors: ['Black', 'Sage'],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    badge: 'Articulated fit',
    rating: 4.8,
    stock: 44,
    image: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80'
  },
  {
    id: 'womens-rain-cap',
    name: "Women's Rainline Cap",
    department: 'womens',
    category: 'Accessories',
    originalPrice: 44,
    price: 37,
    colors: ['Black', 'Olive'],
    sizes: ['One Size'],
    badge: '15% off',
    rating: 4.4,
    stock: 89,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80'
  }
];
